<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Lenovo-PC" name="Default test" tests="6" failures="2" timestamp="13 Jul 2015 09:36:51 GMT" time="30.84" errors="0">
  <testcase name="f" time="5.403" classname="collections.NewTest"/>
  <testcase name="f" time="3.57" classname="collections.NewTest">
    <failure type="java.lang.AssertionError" message="expected [Welcome to Facebook - Log In, Sign Up or Learn More] but found [Welcome to Facebook — Log in, sign up or learn more]">
      <![CDATA[java.lang.AssertionError: expected [Welcome to Facebook - Log In, Sign Up or Learn More] but found [Welcome to Facebook — Log in, sign up or learn more]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at collections.NewTest.f(NewTest.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="11.325" classname="collections.NewTest"/>
  <testcase name="f1" time="1.451" classname="collections.NewTest"/>
  <testcase name="f1" time="2.125" classname="collections.NewTest">
    <failure type="java.lang.AssertionError" message="expected [Welcome to Facebook - Log In, Sign Up or Learn More] but found [Welcome to Facebook — Log in, sign up or learn more]">
      <![CDATA[java.lang.AssertionError: expected [Welcome to Facebook - Log In, Sign Up or Learn More] but found [Welcome to Facebook — Log in, sign up or learn more]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at collections.NewTest.f1(NewTest.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- f1 -->
  <testcase name="f1" time="1.471" classname="collections.NewTest"/>
</testsuite> <!-- Default test -->
